# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-16 10:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Product',
            new_name='Order',
        ),
    ]
