# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-16 10:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20181116_1016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producttype',
            name='product_type',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
