# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-17 10:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20181116_1039'),
    ]

    operations = [
        migrations.CreateModel(
            name='Costing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('collar', models.PositiveIntegerField(blank=True, null=True)),
                ('cutting', models.PositiveIntegerField(blank=True, null=True)),
                ('dying', models.PositiveIntegerField(blank=True, null=True)),
                ('washing', models.PositiveIntegerField(blank=True, null=True)),
                ('others', models.PositiveIntegerField(blank=True, null=True)),
                ('collar_unit_price', models.PositiveIntegerField(blank=True, null=True)),
                ('cutting_unit_price', models.PositiveIntegerField(blank=True, null=True)),
                ('dying_unit_price', models.PositiveIntegerField(blank=True, null=True)),
                ('washing_unit_price', models.PositiveIntegerField(blank=True, null=True)),
                ('others_price', models.PositiveIntegerField(blank=True, null=True)),
                ('total_price', models.PositiveIntegerField(blank=True, null=True)),
                ('total_profit', models.PositiveIntegerField(blank=True, null=True)),
                ('invoic_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.Order')),
            ],
        ),
    ]
