# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-17 10:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_costing'),
    ]

    operations = [
        migrations.AlterField(
            model_name='costing',
            name='total_price',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='costing',
            name='total_profit',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
