# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-17 11:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_auto_20181117_1040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='costing',
            name='collar',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='costing',
            name='collar_unit_price',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='costing',
            name='cutting',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='costing',
            name='cutting_unit_price',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='costing',
            name='dying',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='costing',
            name='dying_unit_price',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='costing',
            name='others',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='costing',
            name='others_price',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='costing',
            name='washing',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='costing',
            name='washing_unit_price',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
