# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-17 11:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_auto_20181117_1113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='costing',
            name='invoic_number',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='products.Order'),
        ),
    ]
