# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-17 12:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_auto_20181117_1121'),
    ]

    operations = [
        migrations.CreateModel(
            name='YearlyProfit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(choices=[('2018', '2018'), ('2019', '2019'), ('2020', '2020')], max_length=10)),
                ('january', models.IntegerField(default=0)),
                ('february', models.IntegerField(default=0)),
                ('march', models.IntegerField(default=0)),
                ('april', models.IntegerField(default=0)),
                ('may', models.IntegerField(default=0)),
                ('june', models.IntegerField(default=0)),
                ('july', models.IntegerField(default=0)),
                ('august', models.IntegerField(default=0)),
                ('september', models.IntegerField(default=0)),
                ('october', models.IntegerField(default=0)),
                ('november', models.IntegerField(default=0)),
                ('december', models.IntegerField(default=0)),
            ],
        ),
    ]
