# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-17 13:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_yearlyprofit'),
    ]

    operations = [
        migrations.AddField(
            model_name='yearlyprofit',
            name='total_month',
            field=models.IntegerField(default=0),
        ),
    ]
